/*
 * Copyright 2005-2006 Paul Cager.
 * 
 * www.paulcager.org
 * 
 * This file is part of cager.parser.
 * 
 * cager.parser is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * cager.parser is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with cager.parser; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/
/* Generated By:JJTree: Do not edit this line. ASTStatement.java */

package cager.parser;

public class ASTStatement extends SimpleNode {
  public ASTStatement(int id) {
    super(id);
  }

  public ASTStatement(VBParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(VBParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }


  /**
 * @uml.property  name="lineNumber"
 */
private long lineNumber = 0;

  /**
 * @param l
 * @uml.property  name="lineNumber"
 */
public void setLineNumber(long l)
  {
	  lineNumber = l;
  }

  public void setLineNumber(String str)
  {
	try
	{
		lineNumber = Long.parseLong(str);
	}
	catch (Exception e)
	{
		lineNumber = 0;
	}
  }

  /**
 * @return
 * @uml.property  name="lineNumber"
 */
public long getLineNumber()
  {
	  return lineNumber;
  }

  /**
 * @uml.property  name="firstOnLine"
 */
public boolean firstOnLine;

  public String toString()
  {
	  String lbl = "";

	  if (parseException != null)
		  lbl = lbl + "!!!!!!!!  ";

	  if (lineNumber != 0)
		  lbl = lbl + "[" + Long.toString(lineNumber) + "] ";

	  return lbl + super.toString();
  }

}
