/* Generated By:JJTree: Do not edit this line. src/cager/parser\VBParserVisitor.java */

package cager.parser;

public interface VBParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTCompilationUnit node, Object data);
  public Object visit(ASTFormItem node, Object data);
  public Object visit(ASTOption node, Object data);
  public Object visit(ASTDeclaration node, Object data);
  public Object visit(ASTEventDeclaration node, Object data);
  public Object visit(ASTTypeDeclaration node, Object data);
  public Object visit(ASTEnumDeclaration node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTImplements node, Object data);
  public Object visit(ASTProcDeclaration node, Object data);
  public Object visit(ASTFormalParamList node, Object data);
  public Object visit(ASTParamSpec node, Object data);
  public Object visit(ASTStatements node, Object data);
  public Object visit(ASTUnrecognisedStatement node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTMethodCall node, Object data);
  public Object visit(ASTLabel node, Object data);
  public Object visit(ASTVarDecl node, Object data);
  public Object visit(ASTUnaryOp node, Object data);
  public Object visit(ASTVarDim node, Object data);
  public Object visit(ASTReDim node, Object data);
  public Object visit(ASTDeclare node, Object data);
  public Object visit(ASTConstDeclaration node, Object data);
  public Object visit(ASTSetStatement node, Object data);
  public Object visit(ASTOnError node, Object data);
  public Object visit(ASTIfStatement node, Object data);
  public Object visit(ASTDoWhileStatement node, Object data);
  public Object visit(ASTDoCondition node, Object data);
  public Object visit(ASTWhileWendStatement node, Object data);
  public Object visit(ASTForEachStatement node, Object data);
  public Object visit(ASTForStatement node, Object data);
  public Object visit(ASTWithStatement node, Object data);
  public Object visit(ASTCaseStatement node, Object data);
  public Object visit(ASTCaseExpr node, Object data);
  public Object visit(ASTArgList node, Object data);
  public Object visit(ASTArgSpec node, Object data);
  public Object visit(ASTExitStatement node, Object data);
  public Object visit(ASTTypeName node, Object data);
  public Object visit(ASTName node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTBinOp node, Object data);
  public Object visit(ASTPrimaryExpression node, Object data);
  public Object visit(ASTLiteral node, Object data);
  public Object visit(ASTArguments node, Object data);
}
