/* Generated By:JJTree: Do not edit this line. src/cager/parser\VBParserTreeConstants.java */

package cager.parser;

public interface VBParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTFORMITEM = 2;
  public int JJTOPTION = 3;
  public int JJTDECLARATION = 4;
  public int JJTEVENTDECLARATION = 5;
  public int JJTTYPEDECLARATION = 6;
  public int JJTENUMDECLARATION = 7;
  public int JJTSTATEMENT = 8;
  public int JJTIMPLEMENTS = 9;
  public int JJTPROCDECLARATION = 10;
  public int JJTFORMALPARAMLIST = 11;
  public int JJTPARAMSPEC = 12;
  public int JJTSTATEMENTS = 13;
  public int JJTUNRECOGNISEDSTATEMENT = 14;
  public int JJTASSIGNMENT = 15;
  public int JJTMETHODCALL = 16;
  public int JJTLABEL = 17;
  public int JJTVARDECL = 18;
  public int JJTUNARYOP = 19;
  public int JJTVARDIM = 20;
  public int JJTREDIM = 21;
  public int JJTDECLARE = 22;
  public int JJTCONSTDECLARATION = 23;
  public int JJTSETSTATEMENT = 24;
  public int JJTONERROR = 25;
  public int JJTIFSTATEMENT = 26;
  public int JJTDOWHILESTATEMENT = 27;
  public int JJTDOCONDITION = 28;
  public int JJTWHILEWENDSTATEMENT = 29;
  public int JJTFOREACHSTATEMENT = 30;
  public int JJTFORSTATEMENT = 31;
  public int JJTWITHSTATEMENT = 32;
  public int JJTCASESTATEMENT = 33;
  public int JJTCASEEXPR = 34;
  public int JJTARGLIST = 35;
  public int JJTARGSPEC = 36;
  public int JJTEXITSTATEMENT = 37;
  public int JJTTYPENAME = 38;
  public int JJTNAME = 39;
  public int JJTEXPRESSION = 40;
  public int JJTBINOP = 41;
  public int JJTPRIMARYEXPRESSION = 42;
  public int JJTLITERAL = 43;
  public int JJTARGUMENTS = 44;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "FormItem",
    "Option",
    "Declaration",
    "EventDeclaration",
    "TypeDeclaration",
    "EnumDeclaration",
    "Statement",
    "Implements",
    "ProcDeclaration",
    "FormalParamList",
    "ParamSpec",
    "Statements",
    "UnrecognisedStatement",
    "Assignment",
    "MethodCall",
    "Label",
    "VarDecl",
    "UnaryOp",
    "VarDim",
    "ReDim",
    "Declare",
    "ConstDeclaration",
    "SetStatement",
    "OnError",
    "IfStatement",
    "DoWhileStatement",
    "DoCondition",
    "WhileWendStatement",
    "ForEachStatement",
    "ForStatement",
    "WithStatement",
    "CaseStatement",
    "CaseExpr",
    "ArgList",
    "ArgSpec",
    "ExitStatement",
    "TypeName",
    "Name",
    "Expression",
    "BinOp",
    "PrimaryExpression",
    "Literal",
    "Arguments",
  };
}
